# Generated by Django 2.2.6 on 2019-11-17 18:55

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.TextField(default='')),
                ('connection_id', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='draw.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='DrawingBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(default='')),
                ('password', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coords', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), size=2), size=2)),
                ('drawing', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='draw.Drawing')),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='draw.DrawingBoard'),
        ),
    ]
