# Generated by Django 2.2.6 on 2019-12-01 17:56

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(default='', max_length=50)),
                ('user_id', models.CharField(default='', max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Drawing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(default='* * M A I N * *', max_length=16)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='draw.Artist')),
            ],
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(default='#000', max_length=20)),
                ('coords', django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), size=2), size=None)),
                ('thickness', models.IntegerField(default=1)),
                ('drawing', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='draw.Drawing')),
            ],
        ),
        migrations.CreateModel(
            name='DrawingBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('password', models.CharField(blank=True, default='', max_length=50)),
                ('artists', models.ManyToManyField(related_name='artist_boards', to='draw.Artist')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='draw.Artist')),
            ],
        ),
        migrations.AddField(
            model_name='drawing',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='draw.DrawingBoard'),
        ),
        migrations.AddField(
            model_name='artist',
            name='boards',
            field=models.ManyToManyField(related_name='board_artists', to='draw.DrawingBoard'),
        ),
    ]
