# Generated by Django 2.2.6 on 2019-12-08 19:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='clear',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='segment',
            name='color',
            field=models.CharField(default='#000', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='segment',
            name='coords',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(default=0), size=2), null=True, size=None),
        ),
    ]
