# Generated by Django 2.2.6 on 2019-12-11 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('draw', '0004_segment_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drawing',
            old_name='end_id',
            new_name='end_index',
        ),
        migrations.RemoveField(
            model_name='drawing',
            name='start_id',
        ),
    ]
